faq/readme.md

The gcloud-go link was mislabeled as gcloud-java causing the markdown to render incorrectly as well as direct the user to incorrect content.

Fixed Broken Stackoverflow Go Link

---

README.md
contributing/readme.md

This contributing guide should be referenced from a brief CONTRIBUTING.md file in the root directory of a gcloud client library project. It is general, and links to external docs such as style guide, set up, etc in order to allow each client library project to supply these specifics.
I'd love to get input/feedback on a few areas:
1. The tone: I pushed the needle far over into "friendly and welcoming". I can easily dial it back if anyone finds it a bit over the top.
1. The content: I made some unilateral decisions about policy, such as "We will try our best to answer within one business day." Obviously, I shouldn't be making these decisions for others.  Think of all such content as placeholders, and let me know what you'd prefer.
1. Links: In three locations I added links to content that …

Add contributing guide

---

contributing/readme.md

`gcloud-node` injects this file into the dom, but all verbiage after the tag name (e.g. `name` in `<project name>`) gets converted to an HTML attribute and ends up rendering like this `<project name="">`. 
Adding some hyphens to work around that.

docs: added hyphens to shell snippet vars

---

authorization/readme.md

They are a bit too little on the doc site.
e.g. http://callmehiphop.github.io/gcloud-node-ghpages/#/authorization?section=create-a-new-service-account

docs: changed auth h6s to h3

---

conduct/CODE_OF_CONDUCT.md

This file should be added to the root directory of gcloud projects.
Follow AngularJS's lead by adapting the Contributor Covenant.

Add code of conduct

---

authorization/readme.md

Also remove the email scope from datastore. It's in the discovery doc but doesn't actually work.
@pcostell Can you confirm that `email` scope doesn't work? I noticed it's not even included in https://www.googleapis.com/discovery/v1/apis/datastore/v1beta3/rest
----
Sources for updating scope lists:
https://www.googleapis.com/discovery/v1/apis/bigquery/v2/rest
https://www.googleapis.com/discovery/v1/apis/datastore/v1beta2/rest
https://www.googleapis.com/discovery/v1/apis/datastore/v1beta3/rest
https://www.googleapis.com/discovery/v1/apis/pubsub/v1/rest
https://www.googleapis.com/discovery/v1/apis/storage/v1/rest

Adding some optional / reduced scopes to auth doc.

---

.travis.yml
deploy-docs.sh

This script should deploy the src/ directory to each repo after every merge to master.
I'm not a good basher, so maybe there's a way to only do this when a push to master actually involved a change to the src/ directory?

Add a build script to deploy docs to each client library

---

.travis.yml
deploy-docs.sh

It's now `gulp-cli`, not `gulp`: https://github.com/gulpjs/gulp/blob/master/docs/getting-started.md
And `verbose` logging was much too verbose.

docs build: install gulp-cli (not gulp)

---

deploy-docs.sh

Travis stopped printing the log, so apparently it is still too verbose.

docs build: turn down npm verbosity

---

site/src/app/index.scss

Currently, [the site](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.27.0/gcloud) gets a few errors in the console:
> Mixed Content: The page at 'https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.27.0/gcloud' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Droid+Sans+Mono|Roboto:300,400,700,700italic,400italic|Open+Sans:300'. This request has been blocked; the content must be served over HTTPS.
(index):1
> Mixed Content: The page at 'https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.27.0/gcloud' was loaded over HTTPS, but requested an insecure stylesheet 'http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'. This request has been blocked; the content must be served over HTTPS.
This …

site: always use https resources

---

site/src/app/docs/docs.html
site/src/app/styles/_main.scss

Fixes a few small layout issues for mobile
* Hides main navigation (it was showing up at the bottom)
* Stops icon overlapping on landing page when menu is open

docs: mobile bug fixes

---

site/src/app/service/service.html

This PR adds a list of `resource.link` & `resource.title` pairs for services/classes. This is to support [the gcloud-ruby docs JSON](https://github.com/quartzmo/gcloud-ruby/blob/gh-pages/json/master/bigquery/table.json), which includes many such links, as shown in this example fragment:
```js
{
id: "table",
metadata: {
name: "Table",
description: "<h1 id="table">Table</h1> <p>A named resource representing a BigQuery table that holds zero or more records. Every table is defined by a schema that may contain nested and repeated fields.</p>",
source: "lib/gcloud/bigquery/table.rb#L66",
resources: [
{
title: "Preparing Data for BigQuery",
link: "https://cloud.google.com/bigquery/preparing-data-for-bigquery"
}
],
...
```
I put this section just after the description and before the method …

site: add service resources links

---

site/src/app/docs/docs.route.js
site/src/app/home/home.route.js

Closes #91 
For whatever reason `/` and `/#` do not match the home route, so when we would hit said routes, they would redirect the user to the latest docs page. 
Good catch, @stephenplusplus!

docs: update routing logic to not skip homepage

---

site/src/app/components/custom-type/custom-type.directive.js

Closes #92 
@quartzmo caught a bug where clicking a custom-type directive link would redirect the user to the latest version, this change will preserve the version.

docs: preserve version on custom type links

---

site/README.md
site/bower.json
site/schemas/manifest.schema.json
site/schemas/service.schema.json
site/schemas/toc.schema.json
site/schemas/types.schema.json
site/src/app/components/page-header/page-header.directive.js
site/src/app/components/page-header/page-header.html
site/src/app/docs/docs.controller.js
site/src/app/docs/docs.html
site/src/app/docs/docs.route.js
site/src/app/docs/docs.service.js
site/src/app/guide/guide.controller.js
site/src/app/service/service.controller.js
site/src/app/service/service.html

Closes https://github.com/GoogleCloudPlatform/gcloud-common/issues/77
Closes https://github.com/GoogleCloudPlatform/gcloud-common/issues/78
This PR aims to give support to some of the requested features needed by both gcloud-ruby and gcloud-php.
[demo](http://callmehiphop.github.io/gcloud-node/#/docs/master/gcloud)
[source files (unminified)](https://github.com/callmehiphop/gcloud-node/tree/gh-pages)
---
* Create a Table of Contents JSON file per version and remove Semver logic
* Tweak code to allow for hidden types
* Remove `metadata` field
* Move `title` key for service overview pages to the <kbd>toc.json</kbd>
* Align JSON more with @blowmage's [schema proposals](https://gist.github.com/blowmage/13be352f40ee7ac5ee48)
---
/cc @blowmage @quartzmo @dwsupplee

site: updates to consume new json schemas

---

site/src/app/styles/_ruby.scss

This change to Ruby code example highlighting, which involves nothing more than a few lines of CSS, is a possible solution to GoogleCloudPlatform/gcloud-ruby#583 ("Code highlighting style in markdown does not match gcloud-common site".)
The change does not seek to perfectly match the Highlight.js Ruby styling, which is rudimentary and inferior to that of Pygments' Ruby highlighting. It simply adjusts a few values, most notably background color, to provide visual cohesion with the Highlight.js examples.
[Demo](http://quartzmo.github.io/gcloud-ruby/#/docs/master/gcloud/bigquery)
Illustration: Pygments (left, with this change) and Highlight.js (right).
/cc @blowmage @jgeewax

site: update Ruby code highlight style

---

site/README.md
site/schemas/manifest.schema.json
site/src/app/docs/docs.service.js
site/src/app/service/service.html

This PR visibly differentiates methods by `type` with a custom, runtime-configured string (symbol or other label.) 
[Demo](http://quartzmo.github.io/gcloud-ruby/#/docs/master/gcloud)
[refs #80]
The PR depends on a new (optional) `methodTypeSymbols` field in `manifest.json`, which maps display characters to method types. (For example: `#` for `instance`.)
This PR replaces outdated #100.

Custom method type symbols

---

site/src/app/components/custom-type/custom-type.directive.js
site/src/app/components/side-nav-link/side-nav-link.directive.js
site/src/app/service/service.controller.js
site/src/app/service/service.html

This PR allows deep linking to a method using the method's `id` rather than its name, which was problematic in Ruby due to duplicate method names in the same namespace.
[Demo](http://quartzmo.github.io/gcloud-ruby/#/docs/master/gcloud)
[refs #79]
The PR depends on adding entries to `types.json` for all methods. The entries for methods should reference the `title` and `contents` values for the parent class (or other namespace). For example:
```js
{
"id": "gcloud",
"title": "Gcloud",
"contents": "gcloud.json"
},
{
"id": "gcloud.new",
"title": "Gcloud",
"contents": "gcloud.json"
},
{
"id": "gcloud#datastore",
"title": "Gcloud",
"contents": "gcloud.json"
},
...
{
"id": "gcloud.datastore",
"title": "Gcloud",
"contents": "gcloud.json"
},
...
```
This PR replaces outdated #100.

site: support links to method ids

---

site/src/app/components/custom-type/custom-type.directive.js
site/src/app/components/side-nav-link/side-nav-link.directive.js
site/src/app/service/service.controller.js
site/src/app/service/service.html

Like PR #109, which is partially reverts, this PR allows deep linking to a method using the method's `id` rather than its name, which was problematic in Ruby due to duplicate method names in the same namespace.
However, unlike #109, this PR preserves the `?method={id}` query param URL signature. Projects without method name conflicts, such as gcloud-node, may simply use the same value for `method.id` as for `method.name` in docs JSON. (gcloud-ruby creates `method.id` by appending `method.type` to `method.name`.)
[Demo](http://quartzmo.github.io/gcloud-ruby/#/docs/master/gcloud)
[closes #113]
/cc @blowmage @stephenplusplus

site: revert method URLs to ?method={id}

---

site/src/app/components/markdown/markdown-highlight.directive.js
site/src/app/components/markdown/markdown.directive.js
site/src/app/docs/docs.service.js
site/src/app/index.constants.js

Closes #116 
This PR will search for code snippets via `<pre><code></code></pre>` tags and auto highlight them. It's possible to bypass this by adding a class of `skip-highlight` to the `<pre>` tag. If the `<pre>` does **not** contain a `<code>` tag, it will **not** apply highlighting.
/cc @quartzmo @stephenplusplus

docs: overload pre tag to apply syntax highlighting

---

site/src/app/service/service.html

Looks like `hljs` is misinterpreting some of our snippets ([`startQuery` as CSS](https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.29.0/bigquery?method=startQuery)).
This will explicitly set all code examples on service pages to the code flavor defined in the <kbd>manifest.json</kbd>

docs: limit scope of highlight languages

---

site/src/app/docs/docs.route.js

Relates to https://github.com/GoogleCloudPlatform/gcloud-ruby/pull/596
When transitioning from a route with a `version` param supplied to one without, the routing logic will redirect the user to the latest version. This change will attempt to resolve the route with the most previously viewed version and if unavailable will then redirect to the latest version.
/cc @blowmage @quartzmo

docs: inherit version when omitted

---

site/src/app/docs/docs.route.js

Relates to https://github.com/GoogleCloudPlatform/gcloud-node/issues/1250
Our redirect for `/docs/:version` was matching non-semver values. Updated the redirect to behave as expected.

site: fix redirect bug

---

site/src/app/service/service.html

I just noticed that gcloud-ruby's dozens of class-level examples are not displayed in the site, although they have been present in the docs JSON. This PR adds a conditional section exposing them.
[Demo](https://quartzmo.github.io/gcloud-ruby/#/docs/master/gcloud/datastore/dataset/lookupresults)
Before (missing examples):
After:
/cc @stephenplusplus @blowmage @jgeewax

site: add service-level examples

---

site/README.md
site/src/app/components/page-header/page-header.directive.js

Closes #133 
This adds an (optional) field to the <kbd>manifest.json</kbd> called `titleDelimiter`. If this is set and a page title is found in the form of an Array, the Angular app will join said array with the value of `titleDelimiter`.
---
<kbd>manifest.json</kbd>
```js
{
"titleDelimiter": "::"
}
```
<kbd>types.json</kbd>
```js
[{
"id": "storage/bucket",
"title": ["Storage", "Bucket"],
"contents": "storage/bucket.json"
}]
```
Yields `Storage::Bucket` for the title of `/docs/{version}/storage/bucket`.
/cc @jgeewax @daspecster

site: add support for configurable title characters

---

site/src/app/service/service.html
site/src/app/styles/_main.scss

When examples are present on the top level of a service, the example container runs right up against the available methods container, as shown in this screenshot:
This change adds a class of `description` to the `article` tag in service.html that contains the description of the service, and sets the `margin-bottom` of `.description` to `2em`, resulting in the following:

Add margin between class description and methods

---

site/README.md
site/src/app/index.run.js

@jdpedrie noticed an issue where 404s were causing the docs site to hang up when not using `gcloud` as the default service. This should fix it :)

Fix for 404 when not using default service of gcloud

---

site/README.md
site/schemas/manifest.schema.json
site/schemas/service.schema.json
site/src/app/components/custom-type/custom-type.directive.js
site/src/app/components/dropdown/dropdown.directive.js
site/src/app/components/dropdown/dropdown.html
site/src/app/components/language-switcher/language-switcher.directive.js
site/src/app/components/language-switcher/language-switcher.html
site/src/app/components/module-switcher/module-switcher.directive.js
site/src/app/components/module-switcher/module-switcher.html
site/src/app/components/side-nav-link/side-nav-link.directive.js
site/src/app/components/version-switcher/version-switcher.html
site/src/app/docs/docs.controller.js
site/src/app/docs/docs.html
site/src/app/docs/docs.route.js
site/src/app/docs/docs.service.js
site/src/app/guide/guide.controller.js
site/src/app/home/home.controller.js
site/src/app/home/home.route.js
site/src/app/index.run.js
site/src/app/service/service.controller.js
site/src/app/service/service.html
site/src/app/styles/_main.scss
site/src/index.html

Closes #52 
This PR aims to add support for multiple modules while also upholding the old way of doing docs.
The big change here is the addition of the `modules` key, this will be an array of modules that can be viewed. Each module should include a default service to be routed to as well as all available versions of said module.
You can specify the default module with the new `defaultModule` key.
```json
{
"lang": "node",
"friendlyLang": "Node.js",
"markdown": "javascript",
"titleDelimiter": "::",
"defaultModule": "google-cloud",
"moduleName": "gcloud-node",
"content": "json",
"home": "home.html",
"package": {
"title": "npm",
"href": "https://www.npmjs.com/package/gcloud"
},
"modules": [{
"id": "google-cloud",
"name": "google-cloud",
"defaultService": "gcloud",
"versions": [
"v0.29.0", …
```

site: modularization support

---

site/src/app/docs/docs.service.js

Add the return description, if set, after the type. Description is rendered on a different line because the markdown parser wraps it in a paragraph tag.
Without description, no change:
(Those screenshots are from different methods)

Expose description on method return

---

site/src/app/docs/docs.controller.js

Fixes  side navigation always being expanded and not collapsing.

Fix navigation expansion by not splitting serviceId.

---

site/README.md
site/src/app/docs/docs.controller.js

This adds support for full & partial service ID matching when deciding on whether or not to expand/collapse a navigation item.

docs: adding support for partial service ids

---

deploy-docs.sh

@callmehiphop per us talking about this earlier and @stephenplusplus [mentioning](https://github.com/GoogleCloudPlatform/gcloud-common/pull/168#discussion_r75883190) it.
Github has repo redirects appear to stay in place until you make a new repo of the same name as the one you renamed. So in theory it looks like the redirect would last a long time.

gcloud-node -> google-cloud-node in deploy-docs.sh.

---

deploy-docs.sh

Repo renamed: https://github.com/GoogleCloudPlatform/google-cloud-ruby/
[refs #172]

Change gcloud-ruby to google-cloud-ruby in docsite updates

---

deploy-docs.sh

We're switching back to sphinx for a little while.
I'll submit a PR to turn this back on when we're rolling again.

Remove google-cloud-python from deploy-docs.sh.

---

README.md
contributing/readme.md
faq/readme.md
troubleshooting/readme.md

Updated the `gcloud-*` references to `google-cloud-*` and `gcloud` to `Google Cloud`. I left the stack overflow tags as-is, because it does not seem that those have changed. I can update if needed.

Update references to `gcloud-*` repos in guides

---

site/src/app/components/version-switcher/version-switcher.directive.spec.js
site/src/app/components/version-switcher/version-switcher.html
site/src/app/styles/_main.scss

This adds a link for the release notes associated with the currently viewed version.
Examples:

site: added release notes link

---

site/src/app/docs/docs.controller.js
site/src/app/docs/docs.html
site/src/app/styles/_main.scss

[Demo](https://quartzmo.github.io/google-cloud-ruby/#/docs/google-cloud/master/google/datastore/v1)
In order to support the design in #207, this PR adds an extra level of nesting support in the left nav. I can produce a demo if needed. Here is a screenshot from my local app:
[closes #209]
/cc @omaray @blowmage @swcloud

site: Add level of nesting to left nav

---

site/schemas/toc.schema.json
site/src/app/docs/docs.controller.js

Replace `matchServiceTitle` in `manifest.json` with `patterns` in `toc.json`.
This change supports multi-word service titles (e.g., 'Natural Language') when the name in the package path is different (e.g., `google/cloud/language`).
The new solution replaces the `matchServiceTitle` introduced in #213 with a more flexible, regexp-based approach. I believe this is safe to do because my understanding is that only google-cloud-ruby is using the `matchServiceTitle` flag.
[closes #216]

site: Add regex-based matching for left nav

---

site/src/app/service/service.html

Always show available methods section. This will reveal the section in the many classes of google-cloud-ruby where the docs for the constructor are private. It should not result in a regression for other platforms, as long as constructors are public and listed first.
[fixes GoogleCloudPlatform/google-cloud-ruby#1593]

site: Update service.html to always show the available methods section

---

site/src/app/docs/docs.route.js
site/src/app/docs/docs.route.spec.js

Preserve query string in otherwise block redirects.
[fixes GoogleCloudPlatform/google-cloud-ruby#1610]

site: Update docs.route otherwise to preserve query string

---

testing/firestore/proto/test.proto

This just makes the generated C# code slightly more idiomatic.
It doesn't require any changes to the tests or the binary result.

Specify C# namespace in test proto

---

contributing/readme.md

Context: The numbering of the [Making changes to Google Cloud](https://github.com/GoogleCloudPlatform/google-cloud-common/blob/master/contributing/readme.md#making-changes-to-google-cloud) section is being restarted whenever there is a code block between two items. That way, the steps to be repeated in the [Verifying your contribution](https://github.com/GoogleCloudPlatform/google-cloud-common/blob/master/contributing/readme.md#verifying-your-contribution) are confusing.
Changes: Add extra spaces before such code blocks, so that the list numbering isn't restarted every time.
Preview: https://github.com/fmachado091/google-cloud-common/blob/master/contributing/readme.md

Fix contributing readme numbering

---

testing/firestore/Makefile
testing/firestore/cmd/generate-firestore-tests/generate-firestore-tests.go

Fix runtime problems: firestore should be using v1 not v1beta1.
Also makes the makefile a bit more approachable by having the
instructions use `go get` and $GOPATH.

fix runtime problems with firestore conformance test generator
