README.md, faq/readme.md, troubleshooting/readme.md
* Changed all questions within the FAQs to use h2 & h3 tags since h4 & h5 looks pretty similar to body text.
* Moved get help section into a separate markdown file to allow for easy addition of project specific faqs
* Added troubleshooting section to main README
=> Updated FAQ Layout

authorization/readme.md
Related to: https://github.com/GoogleCloudPlatform/gcloud-node/pull/734
=> docs: changed image paths to be absolute

site/gulp/build.js, site/src/index.html
Relates to https://github.com/GoogleCloudPlatform/gcloud-common/pull/35#discussion_r51452135
=> docs: changed asset output path to src

deploy-docs.sh
I tried removing `index.html` from the wrong location, so I re-worked this a little bit to hopefully make the process more straightforward. ?.
=> docs build: re-work build script

.travis.yml, deploy-docs.sh
We were missing a few things...
=> docs build: tell Travis this is a Node project

.travis.yml, deploy-docs.sh
Also, make `npm install` output louder logs.
=> docs build: set Travis to run Node 0.12

deploy-docs.sh
These parallel installations don't look like they're working...
=> docs build: skip the parallel installations

deploy-docs.sh
Inspired by: https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/scripts/build.sh#L39
=> docs build: exit if nothing changed

site/src/app/docs/docs.controller.js, site/src/app/service/service.html
Inserted a conditional to check if we should be displaying the library overview/quick start guide on service pages.
=> site: add check for overview file

site/src/app/docs/docs.route.js, site/src/app/index.run.js
Relates to: https://github.com/GoogleCloudPlatform/gcloud-node/issues/1112
Adding logic to redirect user from unknown routes.
=> site: catch-all route logic

deploy-docs.sh, site/gulp/scripts.js
Relates to https://github.com/GoogleCloudPlatform/gcloud-common/pull/97#discussion_r53303019
Created a `lint` task to run on PRs.
=> site: run lint task for PRs

site/src/app/docs/docs.route.js
[refs #78]
This change supports existing routing, titles, and JSON, while adding support for:
* Optional `metadata.title` in content JSON file
* Nesting of content JSON files to any depth
* Navigation to content JSON data that is not listed in a service `nav`
I am not necessarily proposing that this change closes #78, since @blowmage may want to continue work on that issue to enable search and other goals. However, despite being just an incremental (and backwards-compatible) change, it does remove gcloud-ruby's [no. 1 blocker](https://github.com/GoogleCloudPlatform/gcloud-common/issues/78#issuecomment-184798625).
=> Support any JSON path in docsRoutes

site/README.md, site/schemas/manifest.schema.json, site/schemas/service.schema.json
Closes https://github.com/GoogleCloudPlatform/gcloud-common/issues/54
I've made up a basic table of contents for the areas that (I think) could use some documentation. Let me know if you think I'm missing some important features or if something doesn't make sense, etc.
[demo!](https://github.com/callmehiphop/gcloud-common/blob/docs-inception/site/README.md)
=> docs docs: I heard you like docs

site/src/app/components/language-switcher/language-switcher.html
Fixes #110 
Looks like I missed updating the mobile menu links after creating the <kbd>types.json</kbd> via #102
=> site: fixed mobile menu link paths

site/src/app/docs/docs.route.js, site/src/app/index.run.js
Closes #125 
@stephenplusplus caught a bug where `/#/docs` was just hanging out, not going where we were expecting. I made some general updates to the routing logic.
[demo](http://callmehiphop.github.io/gcloud-node/#/) (Ignore the funky home page)
=> site: update routing logic

site/src/app/components/language-switcher/language-switcher.html, site/src/app/index.constants.js, site/src/assets/images/icon-lang-dotnet.svg
Relates to #151 
This adds .NET to the language switcher.
[Demo!](http://callmehiphop.github.io/gcloud-node/#/)
=> site: adding .net to language switcher

site/src/app/service/service.html
Relates to https://github.com/GoogleCloudPlatform/gcloud-node/pull/1475
=> hide getting started when overview key is present

site/src/app/styles/_main.scss
Sorry @callmehiphop, I thought you were going to do this from https://github.com/GoogleCloudPlatform/gcloud-common/issues/158.
LMKWYT
=> Hero banner wrapping fix

site/src/app/docs/docs.route.js
Closes https://github.com/GoogleCloudPlatform/gcloud-node/issues/1504
=> site: add check for guide param when redirecting from old link

deploy-docs.sh
Add `gcloud-python` to receive auto doc site updates/deployments.
=> Add gcloud-python to docsite updates.

deploy-docs.sh
[refs #172]
[closes GoogleCloudPlatform/gcloud-ruby#842]
=> Add gcloud-ruby to docsite updates

site/src/app/index.constants.js
=> site: updated repos for java & ruby

site/README.md, site/schemas/toc.schema.json, site/src/app/docs/docs.controller.js, site/src/app/docs/docs.controller.spec.js, site/src/app/service/service.html
Closes https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1602
**Demo:**
- [site](http://callmehiphop.github.io/gcloud-node/#/docs/bigquery/0.1.2/bigquery)
- [code](https://github.com/callmehiphop/gcloud-node/tree/gh-pages)
=> site: use tagName field for generating source code links

site/src/app/components/deep-link/anchor.directive.js, site/src/app/components/deep-link/anchor.directive.spec.js, site/src/app/docs/docs.route.js, site/src/app/service/service.controller.js
Relates to https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/913
=> site: create anchor directive

site/src/app/index.run.js, site/src/index.html
Update static title 'gcloud' to 'google-cloud'.
Replace static title with manifest.json moduleName.
[fixes #195, fixes GoogleCloudPlatform/google-cloud-ruby#1140]
/cc @stephenplusplus @dwsupplee @jdpedrie @omaray
=> Dynamically set site title in index.html

testing/firestore/Makefile, testing/firestore/README.md, testing/firestore/cmd/generate-firestore-tests/generate-firestore-tests.go
Add the program that generates the tests, and a makefile.
=> testing/firestore: add generator

README.md
=> Add C++ to list of languages

authentication/readme.md
From #211, I thought it might be good to update this a little bit more.
LMKWYT!
=> Update auth guide. to say what to do with key file.

testing/firestore/cmd/generate-firestore-tests/generate-firestore-tests.go
It was pretty hard to understand, so here's filling out a bunch more
details that hopefully will make life easier for the next developer.
=> greatly expand on writetest documentation

contributing/readme.md
Towards https://github.com/googleapis/google-cloud-python/issues/9897
=> docs: add commits convention description in contributing/readme.md
